language: go
go:
  - 1.3

before_install:
  - go get github.com/mitchellh/gox

before_script:
  - gox

deploy:
  provider: releases
  file: launcher
  on:
    repo: dickeyxxx/launcher
    tags: true
    all_branches: true
  api_key:
    secure: sMexrlZBYtLsEXFxt3rV+QZMEUp4+6uPLH7yeW3u9MdS26F74oSmaONp2n5ZzoGf32LVFOdUB0d+gIdD8JDEmGskQgxeJxPwu355fKHNB3m/6Swgtma83OIUxJKE0X47eUJDwfctC0e1EXM/WN+rumSwpVhTCO4mDcS9ZRui7as=
